language: node_js
node_js:
  - "10"
branches:
  only:
    - master
script: yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_DEPLOY_TOKEN
  keep_history: true
  on:
    branch: master
